### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by mmickelson** [taqueci/wp-redmine-wiki#1]
I'm trying to embed a Redmine wiki into a Wordpress page but need more info on the use. What is the key? It isn't working when I put in our redmine details (URL, project, wiki), and just shows the shortcode on the page. There's probably something simple I'm missing.

**Comment by mmickelson** [comment]
Realized the shortcode example shown was missing rwiki `[rwiki url=...`
The key is the user API key found in Redmine. I created a Redmine user with a role that allowed only wiki view and export privileges for security.
I suggest adding to the docs before closing this comment.
Thanks for creating this. It's the only solution I found.

**Comment by taqueci** [comment]
Hi @mmickelson 

Thank you for pointing it out.
